name: CI/CD

on:
  push:
    branches:
      - udaychopade27

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Strapi
        run: npm run build

      - name: Deploy with PM2
        run: |
          pm2 stop all || true
          pm2 start npm --name "strapi" -- start

